import type { TargetSummary, TargetTransport } from "../shared/target-contracts.js";

/** Pinned command-tree source and runtime assessment; no renderer or IPC import. */
export const BEACON_COMMAND_BASELINE_COMMIT = "f8430cecf7ceb5cb332c84fb36aba9b75188802d" as const;

export type BeaconCommandMilestone = "M1" | "M2" | "M4" | "M5" | "M8";
export type BeaconCommandPlatform = "windows" | "linux" | "darwin";
export type BeaconCommandDelivery = "existing" | "planned" | "deferred";
export type BeaconCommandSupport = "source-confirmed" | "pending-runtime" | "session-only" | "operator-only" | "navigation-only" | "unsupported";
export type BeaconResponsePolicy = "none" | "current-preview" | "current-execution" | "proposed-bounded-fetch" | "proposed-native-artifact";
export type BeaconEffectProof = "direct-result" | "requires-requery" | "unverifiable";

export const PINNED_COMPILER_TARGET_ARCHITECTURES = Object.freeze({
  windows: Object.freeze(["386", "amd64", "arm64"] as const),
  linux: Object.freeze(["386", "amd64", "arm64"] as const),
  darwin: Object.freeze(["amd64", "arm64"] as const),
} as const); // server/generate/binaries.go at the pinned baseline.

export const BEACON_RESPONSE_CEILINGS = Object.freeze({
  none: 0,
  "current-preview": 64 * 1_024,
  "current-execution": (2 * 1_024 * 1_024) + (64 * 1_024),
  "proposed-bounded-fetch": 1 * 1_024 * 1_024,
  "proposed-native-artifact": 64 * 1_024 * 1_024,
  /** Upload input bytes are a separate proposed main-owned request limit. */
  proposedUploadInputBytes: 64 * 1_024 * 1_024,
} as const);

export interface BeaconRpcStep {
  readonly rpcMethod: string;
  /** The queued protobuf payload type (usually also BeaconTask.Description). */
  readonly requestType: string;
  /** Server RPC input when it transforms a different request into the queued type. */
  readonly rpcRequestType?: string;
  /** Server RPC return type; it need not be a fetched beacon task result (Kill is special). */
  readonly responseType: string;
  readonly taskResponseType?: "none";
  readonly taskDescription: string;
}
export type BeaconCommandRoute =
  | { readonly kind: "task"; readonly steps: readonly BeaconRpcStep[]; readonly responsePolicy: BeaconResponsePolicy; readonly maximumResponseBytes: number; readonly effectProof: BeaconEffectProof }
  | { readonly kind: "existing-execution"; readonly executionOperationId: string; readonly task: Extract<BeaconCommandRoute, { kind: "task" }> }
  | { readonly kind: "existing-main"; readonly operationId: string; readonly task?: Extract<BeaconCommandRoute, { kind: "task" }> }
  | { readonly kind: "metadata"; readonly fields: readonly string[] }
  | { readonly kind: "hybrid"; readonly fields: readonly string[]; readonly windowsSteps: readonly BeaconRpcStep[]; readonly responsePolicy: "proposed-bounded-fetch"; readonly maximumResponseBytes: number }
  | { readonly kind: "navigation"; readonly reason: string }
  | { readonly kind: "operator-workflow"; readonly reason: string }
  | { readonly kind: "deferred-workflow"; readonly reason: string };

export interface BeaconProtocolStep {
  readonly rpcMethod: string;
  readonly rpcRequestType: string;
  readonly rpcResponseType: string;
}

export interface BeaconCommandDescriptor {
  /** RPC protocol identity, including deferred workflows; never a dispatch table. */
  readonly protocol: readonly BeaconProtocolStep[];
  readonly milestone: BeaconCommandMilestone;
  readonly delivery: BeaconCommandDelivery;
  readonly support: BeaconCommandSupport;
  readonly platforms: readonly BeaconCommandPlatform[];
  /** Effective per-platform build targets at the pinned baseline. */
  readonly architecturesByPlatform: Readonly<Partial<typeof PINNED_COMPILER_TARGET_ARCHITECTURES>>;
  readonly transports: readonly TargetTransport[];
  readonly source: Readonly<{ file: string; line: number }>;
  readonly runtimeEvidence: readonly string[];
  /** Standard beacon transports are source candidates; pivot variants remain withheld pending proof. */
  readonly transportReview: string;
  readonly consoleOptions: readonly string[];
  /** Each reviewed console option appears in exactly one boundary bucket. */
  readonly optionBoundary: Readonly<{ request: readonly string[]; local: readonly string[]; main: readonly string[]; pending: readonly string[] }>;
  readonly route: BeaconCommandRoute;
}

const COMMON_BEACON_TRANSPORTS = Object.freeze(["mtls", "http", "https", "dns", "wg"] as const);
const WG_TRANSPORT = Object.freeze(["wg"] as const);

function task(steps: readonly BeaconRpcStep[], responsePolicy: BeaconResponsePolicy, effectProof: BeaconEffectProof): Extract<BeaconCommandRoute, { kind: "task" }> {
  return { kind: "task", steps, responsePolicy, maximumResponseBytes: BEACON_RESPONSE_CEILINGS[responsePolicy], effectProof };
}
function executionTask(executionOperationId: string, taskRoute: Extract<BeaconCommandRoute, { kind: "task" }>): BeaconCommandRoute {
  return { kind: "existing-execution", executionOperationId, task: taskRoute };
}
function existingMain(operationId: string, taskRoute?: Extract<BeaconCommandRoute, { kind: "task" }>): BeaconCommandRoute {
  return taskRoute ? { kind: "existing-main", operationId, task: taskRoute } : { kind: "existing-main", operationId };
}
function metadata(fields: readonly string[]): BeaconCommandRoute { return { kind: "metadata", fields }; }
function hybrid(fields: readonly string[], windowsSteps: readonly BeaconRpcStep[]): BeaconCommandRoute {
  return { kind: "hybrid", fields, windowsSteps, responsePolicy: "proposed-bounded-fetch", maximumResponseBytes: BEACON_RESPONSE_CEILINGS["proposed-bounded-fetch"] };
}
function navigation(reason: string): BeaconCommandRoute { return { kind: "navigation", reason }; }
function operatorWorkflow(reason: string): BeaconCommandRoute { return { kind: "operator-workflow", reason }; }
function deferred(reason: string): BeaconCommandRoute { return { kind: "deferred-workflow", reason }; }

function descriptor(
  milestone: BeaconCommandMilestone, delivery: BeaconCommandDelivery, support: BeaconCommandSupport,
  platforms: readonly BeaconCommandPlatform[], source: BeaconCommandDescriptor["source"],
  runtimeEvidence: readonly string[], consoleOptions: readonly string[], optionBoundary: BeaconCommandDescriptor["optionBoundary"],
  route: BeaconCommandRoute, protocol: readonly BeaconProtocolStep[], transports: readonly TargetTransport[] = COMMON_BEACON_TRANSPORTS,
): BeaconCommandDescriptor {
  const architecturesByPlatform = Object.fromEntries(
    platforms.map((platform) => [platform, PINNED_COMPILER_TARGET_ARCHITECTURES[platform]]),
  ) as BeaconCommandDescriptor["architecturesByPlatform"];
  return { protocol, milestone, delivery, support, platforms, architecturesByPlatform, transports, source, runtimeEvidence, transportReview: "Pinned command tree says any; named-pipe and TCP-pivot beacon transport paths remain withheld pending runtime proof.", consoleOptions, optionBoundary, route };
}

/** 92 reviewed beacon-visible parity rows. A planned row is data, not a new RPC authority. */
export const BEACON_COMMAND_MATRIX = deepFreeze({
  "implant.ai": descriptor("M8", "planned", "operator-only", ["windows", "linux", "darwin"], {"file": "client/command/ai/commands.go", "line": 45}, ["client/command/ai/commands.go"], [], {"request": [], "local": [], "main": [], "pending": []}, operatorWorkflow("Server-backed operator TUI."), []),
  "implant.aka": descriptor("M8", "planned", "operator-only", ["windows", "linux", "darwin"], {"file": "client/command/aka/commands.go", "line": 21}, ["client/command/aka/commands.go"], [], {"request": [], "local": [], "main": [], "pending": []}, operatorWorkflow("Operator alias workflow."), []),
  "implant.aka.create": descriptor("M8", "planned", "operator-only", ["windows", "linux", "darwin"], {"file": "client/command/aka/commands.go", "line": 33}, ["client/command/aka/commands.go"], [], {"request": [], "local": [], "main": [], "pending": []}, operatorWorkflow("Operator alias workflow."), []),
  "implant.aka.delete": descriptor("M8", "planned", "operator-only", ["windows", "linux", "darwin"], {"file": "client/command/aka/commands.go", "line": 45}, ["client/command/aka/commands.go"], [], {"request": [], "local": [], "main": [], "pending": []}, operatorWorkflow("Operator alias workflow."), []),
  "implant.backdoor": descriptor("M4", "planned", "session-only", ["windows"], {"file": "client/command/backdoor/commands.go", "line": 24}, ["server/rpc/rpc-backdoor.go"], ["profile", "timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": ["profile"]}, deferred("Pinned server RPC requires SessionID; no beacon task route."), [{"rpcMethod": "Backdoor", "rpcRequestType": "BackdoorReq", "rpcResponseType": "Backdoor"}]),
  "implant.background": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/sessions/commands.go", "line": 145}, ["client/command/sessions/background.go"], ["timeout"], {"request": [], "local": ["timeout"], "main": [], "pending": []}, operatorWorkflow("Changes local active-target selection."), []),
  "implant.cat": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 136}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["colorize-output", "file-type", "hex", "loot", "name", "timeout", "type"], {"request": [], "local": ["colorize-output", "file-type", "hex", "loot", "name", "type"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Download", "requestType": "DownloadReq", "responseType": "Download", "taskDescription": "DownloadReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "Download", "rpcRequestType": "DownloadReq", "rpcResponseType": "Download"}]),
  "implant.cd": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 108}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Cd", "requestType": "CdReq", "responseType": "Pwd", "taskDescription": "CdReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Cd", "rpcRequestType": "CdReq", "rpcResponseType": "Pwd"}]),
  "implant.chmod": descriptor("M2", "planned", "source-confirmed", ["linux", "darwin"], {"file": "client/command/privilege/commands.go", "line": 107}, ["implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["recursive", "timeout"], {"request": ["recursive"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Chmod", "requestType": "ChmodReq", "responseType": "Chmod", "taskDescription": "ChmodReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Chmod", "rpcRequestType": "ChmodReq", "rpcResponseType": "Chmod"}]),
  "implant.chown": descriptor("M2", "planned", "source-confirmed", ["linux", "darwin"], {"file": "client/command/privilege/commands.go", "line": 126}, ["implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["recursive", "timeout"], {"request": ["recursive"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Chown", "requestType": "ChownReq", "responseType": "Chown", "taskDescription": "ChownReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Chown", "rpcRequestType": "ChownReq", "rpcResponseType": "Chown"}]),
  "implant.chtimes": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/privilege/commands.go", "line": 146}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["rfc1123", "rfc3339", "timeout", "unix", "unix-ms"], {"request": [], "local": [], "main": ["rfc1123", "rfc3339", "timeout", "unix", "unix-ms"], "pending": []}, task([{"rpcMethod": "Chtimes", "requestType": "ChtimesReq", "responseType": "Chtimes", "taskDescription": "ChtimesReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Chtimes", "rpcRequestType": "ChtimesReq", "rpcResponseType": "Chtimes"}]),
  "implant.close": descriptor("M1", "deferred", "session-only", ["windows", "linux", "darwin"], {"file": "client/command/sessions/commands.go", "line": 181}, ["client/command/sessions/close.go", "server/rpc/rpc-sessions.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, deferred("Session-only close action; no beacon route."), [{"rpcMethod": "CloseSession", "rpcRequestType": "CloseSession", "rpcResponseType": "Empty"}]),
  "implant.cp": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 40}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Cp", "requestType": "CpReq", "responseType": "Cp", "taskDescription": "CpReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Cp", "rpcRequestType": "CpReq", "rpcResponseType": "Cp"}]),
  "implant.dllhijack": descriptor("M4", "planned", "session-only", ["windows"], {"file": "client/command/dllhijack/commands.go", "line": 25}, ["server/rpc/rpc-hijack.go"], ["file", "profile", "reference-file", "reference-path", "timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": ["file", "profile", "reference-file", "reference-path"]}, deferred("Pinned server RPC requires SessionID; no beacon task route."), [{"rpcMethod": "HijackDLL", "rpcRequestType": "DllHijackReq", "rpcResponseType": "DllHijack"}]),
  "implant.docs": descriptor("M8", "planned", "operator-only", ["windows", "linux", "darwin"], {"file": "client/command/docs/commands.go", "line": 27}, ["client/command/docs/commands.go"], [], {"request": [], "local": [], "main": [], "pending": []}, operatorWorkflow("Operator documentation workflow."), []),
  "implant.download": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 157}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["file-type", "loot", "name", "recurse", "timeout", "type"], {"request": ["recurse"], "local": ["file-type", "loot", "name", "type"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Download", "requestType": "DownloadReq", "responseType": "Download", "taskDescription": "DownloadReq"}], "proposed-native-artifact", "direct-result"), [{"rpcMethod": "Download", "rpcRequestType": "DownloadReq", "rpcResponseType": "Download"}]),
  "implant.edit": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/edit/commands.go", "line": 20}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["line-numbers", "syntax", "syntax-select", "timeout"], {"request": [], "local": ["line-numbers", "syntax", "syntax-select"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Download", "requestType": "DownloadReq", "responseType": "Download", "taskDescription": "DownloadReq"}, {"rpcMethod": "Upload", "requestType": "UploadReq", "responseType": "Upload", "taskDescription": "UploadReq"}], "proposed-native-artifact", "requires-requery"), [{"rpcMethod": "Download", "rpcRequestType": "DownloadReq", "rpcResponseType": "Download"}, {"rpcMethod": "Upload", "rpcRequestType": "UploadReq", "rpcResponseType": "Upload"}]),
  "implant.env": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/environment/commands.go", "line": 21}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "GetEnv", "requestType": "EnvReq", "responseType": "EnvInfo", "taskDescription": "EnvReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "GetEnv", "rpcRequestType": "EnvReq", "rpcResponseType": "EnvInfo"}]),
  "implant.env.set": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/environment/commands.go", "line": 36}, ["client/command/environment/commands.go", "server/rpc/rpc.go"], [], {"request": [], "local": [], "main": [], "pending": []}, existingMain("target.env-set", task([{"rpcMethod": "SetEnv", "requestType": "SetEnvReq", "responseType": "SetEnv", "taskDescription": "SetEnvReq"}], "current-preview", "requires-requery")), [{"rpcMethod": "SetEnv", "rpcRequestType": "SetEnvReq", "rpcResponseType": "SetEnv"}]),
  "implant.env.unset": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/environment/commands.go", "line": 51}, ["client/command/environment/commands.go", "server/rpc/rpc.go"], [], {"request": [], "local": [], "main": [], "pending": []}, existingMain("target.env-unset", task([{"rpcMethod": "UnsetEnv", "requestType": "UnsetEnvReq", "responseType": "UnsetEnv", "taskDescription": "UnsetEnvReq"}], "current-preview", "requires-requery")), [{"rpcMethod": "UnsetEnv", "rpcRequestType": "UnsetEnvReq", "rpcResponseType": "UnsetEnv"}]),
  "implant.execute": descriptor("M4", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/exec/commands.go", "line": 23}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["background", "env", "env-inheritance", "hidden", "ignore-stderr", "loot", "name", "output", "ppid", "save", "stderr", "stdout", "timeout", "token"], {"request": [], "local": ["loot", "name", "save"], "main": ["timeout"], "pending": ["background", "env", "env-inheritance", "hidden", "ignore-stderr", "output", "ppid", "stderr", "stdout", "token"]}, executionTask("execution.process", task([{"rpcMethod": "Execute", "requestType": "ExecuteReq", "responseType": "Execute", "taskDescription": "ExecuteReq"}, {"rpcMethod": "ExecuteWindows", "requestType": "ExecuteWindowsReq", "responseType": "Execute", "taskDescription": "ExecuteWindowsReq"}], "current-execution", "requires-requery")), [{"rpcMethod": "Execute", "rpcRequestType": "ExecuteReq", "rpcResponseType": "Execute"}, {"rpcMethod": "ExecuteWindows", "rpcRequestType": "ExecuteWindowsReq", "rpcResponseType": "Execute"}]),
  "implant.execute-assembly": descriptor("M4", "existing", "source-confirmed", ["windows"], {"file": "client/command/exec/commands.go", "line": 69}, ["implant/sliver/handlers/handlers_windows.go"], ["amsi-bypass", "app-domain", "arch", "class", "etw-bypass", "in-process", "loot", "method", "name", "ppid", "process", "process-arguments", "runtime", "save", "timeout"], {"request": [], "local": ["loot", "name", "save"], "main": ["timeout"], "pending": ["amsi-bypass", "app-domain", "arch", "class", "etw-bypass", "in-process", "method", "ppid", "process", "process-arguments", "runtime"]}, executionTask("execution.assembly", task([{"rpcMethod": "ExecuteAssembly", "requestType": "InvokeExecuteAssemblyReq", "responseType": "ExecuteAssembly", "taskDescription": "InvokeExecuteAssemblyReq", "rpcRequestType": "ExecuteAssemblyReq"}, {"rpcMethod": "ExecuteAssembly", "requestType": "InvokeInProcExecuteAssemblyReq", "responseType": "ExecuteAssembly", "taskDescription": "InvokeInProcExecuteAssemblyReq", "rpcRequestType": "ExecuteAssemblyReq"}], "current-execution", "requires-requery")), [{"rpcMethod": "ExecuteAssembly", "rpcRequestType": "ExecuteAssemblyReq", "rpcResponseType": "ExecuteAssembly"}, {"rpcMethod": "ExecuteAssembly", "rpcRequestType": "ExecuteAssemblyReq", "rpcResponseType": "ExecuteAssembly"}]),
  "implant.execute-shellcode": descriptor("M4", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/exec/commands.go", "line": 104}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["architecture", "interactive", "iterations", "pid", "process", "rwx-pages", "shellcode-bypass", "shellcode-compress", "shellcode-entropy", "shellcode-exitopt", "shellcode-headers", "shellcode-oep", "shellcode-thread", "shellcode-unicode", "shikata-ga-nai", "timeout"], {"request": ["pid"], "local": [], "main": ["timeout"], "pending": ["architecture", "interactive", "iterations", "process", "rwx-pages", "shellcode-bypass", "shellcode-compress", "shellcode-entropy", "shellcode-exitopt", "shellcode-headers", "shellcode-oep", "shellcode-thread", "shellcode-unicode", "shikata-ga-nai"]}, executionTask("execution.shellcode", task([{"rpcMethod": "Task", "requestType": "TaskReq", "responseType": "Task", "taskDescription": "TaskReq"}], "current-execution", "unverifiable")), [{"rpcMethod": "Task", "rpcRequestType": "TaskReq", "rpcResponseType": "Task"}]),
  "implant.execute.children": descriptor("M4", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/exec/commands.go", "line": 55}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, executionTask("execution.children", task([{"rpcMethod": "ExecuteChildren", "requestType": "ExecuteChildrenReq", "responseType": "ExecuteChildren", "taskDescription": "ExecuteChildrenReq"}], "proposed-bounded-fetch", "direct-result")), [{"rpcMethod": "ExecuteChildren", "rpcRequestType": "ExecuteChildrenReq", "rpcResponseType": "ExecuteChildren"}]),
  "implant.getgid": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/info/commands.go", "line": 78}, ["client/command/info/info.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, metadata(["gid"]), []),
  "implant.getpid": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/info/commands.go", "line": 52}, ["client/command/info/info.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, metadata(["pid"]), []),
  "implant.getprivs": descriptor("M4", "planned", "source-confirmed", ["windows"], {"file": "client/command/privilege/commands.go", "line": 170}, ["implant/sliver/handlers/handlers_windows.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, executionTask("privilege.get", task([{"rpcMethod": "GetPrivs", "requestType": "GetPrivsReq", "responseType": "GetPrivs", "taskDescription": "GetPrivsReq"}], "proposed-bounded-fetch", "direct-result")), [{"rpcMethod": "GetPrivs", "rpcRequestType": "GetPrivsReq", "rpcResponseType": "GetPrivs"}]),
  "implant.getuid": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/info/commands.go", "line": 65}, ["client/command/info/info.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, metadata(["uid"]), []),
  "implant.grep": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 255}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["after", "before", "colorize-output", "context", "exact", "insensitive", "loot", "name", "recursive", "timeout", "type"], {"request": ["after", "before", "context", "recursive"], "local": ["colorize-output", "loot", "name", "type"], "main": ["timeout"], "pending": ["exact", "insensitive"]}, task([{"rpcMethod": "Grep", "requestType": "GrepReq", "responseType": "Grep", "taskDescription": "GrepReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "Grep", "rpcRequestType": "GrepReq", "rpcResponseType": "Grep"}]),
  "implant.head": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 283}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["bytes", "colorize-output", "file-type", "hex", "lines", "loot", "name", "timeout", "type"], {"request": ["bytes", "lines"], "local": ["colorize-output", "file-type", "hex", "loot", "name", "type"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Download", "requestType": "DownloadReq", "responseType": "Download", "taskDescription": "DownloadReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "Download", "rpcRequestType": "DownloadReq", "rpcResponseType": "Download"}]),
  "implant.hex-edit": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/hexedit/commands.go", "line": 21}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["max-size", "offset", "timeout"], {"request": ["max-size"], "local": ["offset"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Download", "requestType": "DownloadReq", "responseType": "Download", "taskDescription": "DownloadReq"}, {"rpcMethod": "Upload", "requestType": "UploadReq", "responseType": "Upload", "taskDescription": "UploadReq"}], "proposed-native-artifact", "requires-requery"), [{"rpcMethod": "Download", "rpcRequestType": "DownloadReq", "rpcResponseType": "Download"}, {"rpcMethod": "Upload", "rpcRequestType": "UploadReq", "rpcResponseType": "Upload"}]),
  "implant.ifconfig": descriptor("M2", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/network/commands.go", "line": 19}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["all", "timeout"], {"request": [], "local": ["all"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Ifconfig", "requestType": "IfconfigReq", "responseType": "Ifconfig", "taskDescription": "IfconfigReq"}], "current-preview", "direct-result"), [{"rpcMethod": "Ifconfig", "rpcRequestType": "IfconfigReq", "rpcResponseType": "Ifconfig"}]),
  "implant.impersonate": descriptor("M4", "planned", "source-confirmed", ["windows"], {"file": "client/command/privilege/commands.go", "line": 44}, ["implant/sliver/handlers/handlers_windows.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, executionTask("privilege.impersonate", task([{"rpcMethod": "Impersonate", "requestType": "ImpersonateReq", "responseType": "Impersonate", "taskDescription": "ImpersonateReq"}], "proposed-bounded-fetch", "requires-requery")), [{"rpcMethod": "Impersonate", "rpcRequestType": "ImpersonateReq", "rpcResponseType": "Impersonate"}]),
  "implant.info": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/info/commands.go", "line": 104}, ["client/command/info/info.go"], ["timeout"], {"request": [], "local": ["timeout"], "main": [], "pending": []}, metadata(["summary"]), []),
  "implant.interactive": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/sessions/commands.go", "line": 158}, ["client/command/sessions/interactive.go", "server/rpc/rpc-sessions.go"], ["delay", "dns", "http", "mtls", "named-pipe", "tcp-pivot", "timeout", "wg"], {"request": ["delay"], "local": [], "main": ["dns", "http", "mtls", "named-pipe", "tcp-pivot", "timeout", "wg"], "pending": []}, existingMain("beacon.open-session", task([{"rpcMethod": "OpenSession", "requestType": "OpenSession", "responseType": "OpenSession", "taskDescription": "OpenSession"}], "current-preview", "unverifiable")), [{"rpcMethod": "OpenSession", "rpcRequestType": "OpenSession", "rpcResponseType": "OpenSession"}]),
  "implant.kill": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/kill/commands.go", "line": 19}, ["server/rpc/rpc-kill.go"], ["force", "timeout"], {"request": ["force"], "local": [], "main": ["timeout"], "pending": []}, existingMain("target.terminate", task([{"rpcMethod": "Kill", "requestType": "Request", "rpcRequestType": "KillReq", "responseType": "Empty", "taskDescription": "KillReq", "taskResponseType": "none"}], "none", "unverifiable")), [{"rpcMethod": "Kill", "rpcRequestType": "KillReq", "rpcResponseType": "Empty"}]),
  "implant.ls": descriptor("M2", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 58}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["modified", "reverse", "size", "timeout"], {"request": [], "local": ["modified", "reverse", "size"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Ls", "requestType": "LsReq", "responseType": "Ls", "taskDescription": "LsReq"}], "current-preview", "direct-result"), [{"rpcMethod": "Ls", "rpcRequestType": "LsReq", "rpcResponseType": "Ls"}]),
  "implant.make-token": descriptor("M4", "planned", "source-confirmed", ["windows"], {"file": "client/command/privilege/commands.go", "line": 90}, ["implant/sliver/handlers/handlers_windows.go"], ["domain", "logon-type", "password", "timeout", "username"], {"request": [], "local": [], "main": ["timeout"], "pending": ["domain", "logon-type", "password", "username"]}, executionTask("privilege.make-token", task([{"rpcMethod": "MakeToken", "requestType": "MakeTokenReq", "responseType": "MakeToken", "taskDescription": "MakeTokenReq"}], "proposed-bounded-fetch", "requires-requery")), [{"rpcMethod": "MakeToken", "rpcRequestType": "MakeTokenReq", "rpcResponseType": "MakeToken"}]),
  "implant.memfiles": descriptor("M2", "planned", "source-confirmed", ["linux"], {"file": "client/command/filesystem/commands.go", "line": 206}, ["implant/sliver/handlers/handlers_linux.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "MemfilesList", "requestType": "MemfilesListReq", "responseType": "Ls", "taskDescription": "MemfilesListReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "MemfilesList", "rpcRequestType": "MemfilesListReq", "rpcResponseType": "Ls"}]),
  "implant.memfiles.add": descriptor("M2", "planned", "source-confirmed", ["linux"], {"file": "client/command/filesystem/commands.go", "line": 218}, ["implant/sliver/handlers/handlers_linux.go"], [], {"request": [], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "MemfilesAdd", "requestType": "MemfilesAddReq", "responseType": "MemfilesAdd", "taskDescription": "MemfilesAddReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "MemfilesAdd", "rpcRequestType": "MemfilesAddReq", "rpcResponseType": "MemfilesAdd"}]),
  "implant.memfiles.rm": descriptor("M2", "planned", "source-confirmed", ["linux"], {"file": "client/command/filesystem/commands.go", "line": 229}, ["implant/sliver/handlers/handlers_linux.go"], [], {"request": [], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "MemfilesRm", "requestType": "MemfilesRmReq", "responseType": "MemfilesRm", "taskDescription": "MemfilesRmReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "MemfilesRm", "rpcRequestType": "MemfilesRmReq", "rpcResponseType": "MemfilesRm"}]),
  "implant.migrate": descriptor("M4", "existing", "source-confirmed", ["windows"], {"file": "client/command/exec/commands.go", "line": 196}, ["implant/sliver/handlers/handlers_windows.go"], ["pid", "process-name", "shellcode-encoder", "timeout"], {"request": ["pid"], "local": [], "main": ["timeout"], "pending": ["process-name", "shellcode-encoder"]}, executionTask("execution.migrate", task([{"rpcMethod": "Migrate", "requestType": "InvokeMigrateReq", "responseType": "Migrate", "taskDescription": "InvokeMigrateReq", "rpcRequestType": "MigrateReq"}], "current-execution", "requires-requery")), [{"rpcMethod": "Migrate", "rpcRequestType": "MigrateReq", "rpcResponseType": "Migrate"}]),
  "implant.mkdir": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 93}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Mkdir", "requestType": "MkdirReq", "responseType": "Mkdir", "taskDescription": "MkdirReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Mkdir", "rpcRequestType": "MkdirReq", "rpcResponseType": "Mkdir"}]),
  "implant.mount": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 241}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Mount", "requestType": "MountReq", "responseType": "Mount", "taskDescription": "MountReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "Mount", "rpcRequestType": "MountReq", "rpcResponseType": "Mount"}]),
  "implant.msf": descriptor("M4", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/exec/commands.go", "line": 217}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["encoder", "iterations", "lhost", "lport", "payload", "timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": ["encoder", "iterations", "lhost", "lport", "payload"]}, executionTask("execution.msf", task([{"rpcMethod": "Msf", "requestType": "TaskReq", "responseType": "Task", "taskDescription": "TaskReq", "rpcRequestType": "MSFReq"}], "current-execution", "unverifiable")), [{"rpcMethod": "Msf", "rpcRequestType": "MSFReq", "rpcResponseType": "Task"}]),
  "implant.msf-inject": descriptor("M4", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/exec/commands.go", "line": 236}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["encoder", "iterations", "lhost", "lport", "payload", "pid", "timeout"], {"request": ["pid"], "local": [], "main": ["timeout"], "pending": ["encoder", "iterations", "lhost", "lport", "payload"]}, executionTask("execution.msf-inject", task([{"rpcMethod": "MsfRemote", "requestType": "TaskReq", "responseType": "Task", "taskDescription": "TaskReq", "rpcRequestType": "MSFRemoteReq"}], "current-execution", "unverifiable")), [{"rpcMethod": "MsfRemote", "rpcRequestType": "MSFRemoteReq", "rpcResponseType": "Task"}]),
  "implant.mv": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 22}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Mv", "requestType": "MvReq", "responseType": "Mv", "taskDescription": "MvReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Mv", "rpcRequestType": "MvReq", "rpcResponseType": "Mv"}]),
  "implant.netstat": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/network/commands.go", "line": 33}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["ip4", "ip6", "listen", "numeric", "tcp", "timeout", "udp"], {"request": ["ip4", "ip6", "listen", "tcp", "udp"], "local": ["numeric"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Netstat", "requestType": "NetstatReq", "responseType": "Netstat", "taskDescription": "NetstatReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "Netstat", "rpcRequestType": "NetstatReq", "rpcResponseType": "Netstat"}]),
  "implant.ping": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/info/commands.go", "line": 39}, ["server/rpc/rpc.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, existingMain("target.ping", task([{"rpcMethod": "Ping", "requestType": "Ping", "responseType": "Ping", "taskDescription": "Ping"}], "current-preview", "direct-result")), [{"rpcMethod": "Ping", "rpcRequestType": "Ping", "rpcResponseType": "Ping"}]),
  "implant.pivots": descriptor("M5", "planned", "session-only", ["windows", "linux", "darwin"], {"file": "client/command/pivots/commands.go", "line": 21}, ["client/command/pivots/commands.go", "implant/sliver/runner/runner.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, deferred("Pivot listener workflow requires a session receive loop in the pinned runtime."), [{"rpcMethod": "PivotSessionListeners", "rpcRequestType": "PivotListenersReq", "rpcResponseType": "PivotListeners"}]),
  "implant.pivots.details": descriptor("M5", "planned", "session-only", ["windows", "linux", "darwin"], {"file": "client/command/pivots/commands.go", "line": 78}, ["client/command/pivots/commands.go", "implant/sliver/runner/runner.go"], ["id"], {"request": [], "local": ["id"], "main": [], "pending": []}, deferred("Pivot listener workflow requires a session receive loop in the pinned runtime."), [{"rpcMethod": "PivotSessionListeners", "rpcRequestType": "PivotListenersReq", "rpcResponseType": "PivotListeners"}]),
  "implant.pivots.graph": descriptor("M5", "planned", "operator-only", ["windows", "linux", "darwin"], {"file": "client/command/pivots/commands.go", "line": 94}, ["client/command/pivots/commands.go", "implant/sliver/runner/runner.go"], [], {"request": [], "local": [], "main": [], "pending": []}, operatorWorkflow("Server-owned pivot topology query; no implant task."), [{"rpcMethod": "PivotGraph", "rpcRequestType": "Empty", "rpcResponseType": "PivotGraph"}]),
  "implant.pivots.named-pipe": descriptor("M5", "planned", "session-only", ["windows"], {"file": "client/command/pivots/commands.go", "line": 34}, ["client/command/pivots/commands.go", "implant/sliver/runner/runner.go"], ["allow-all", "bind"], {"request": ["allow-all", "bind"], "local": [], "main": [], "pending": []}, deferred("Pivot listener workflow requires a session receive loop in the pinned runtime."), [{"rpcMethod": "PivotStartListener", "rpcRequestType": "PivotStartListenerReq", "rpcResponseType": "PivotListener"}]),
  "implant.pivots.stop": descriptor("M5", "planned", "session-only", ["windows", "linux", "darwin"], {"file": "client/command/pivots/commands.go", "line": 62}, ["client/command/pivots/commands.go", "implant/sliver/runner/runner.go"], ["id"], {"request": ["id"], "local": [], "main": [], "pending": []}, deferred("Pivot listener workflow requires a session receive loop in the pinned runtime."), [{"rpcMethod": "PivotSessionListeners", "rpcRequestType": "PivotListenersReq", "rpcResponseType": "PivotListeners"}, {"rpcMethod": "PivotStopListener", "rpcRequestType": "PivotStopListenerReq", "rpcResponseType": "Empty"}]),
  "implant.pivots.tcp": descriptor("M5", "planned", "session-only", ["windows", "linux", "darwin"], {"file": "client/command/pivots/commands.go", "line": 48}, ["client/command/pivots/commands.go", "implant/sliver/runner/runner.go"], ["bind", "lport"], {"request": ["bind", "lport"], "local": [], "main": [], "pending": []}, deferred("Pivot listener workflow requires a session receive loop in the pinned runtime."), [{"rpcMethod": "PivotStartListener", "rpcRequestType": "PivotStartListenerReq", "rpcResponseType": "PivotListener"}]),
  "implant.procdump": descriptor("M2", "planned", "source-confirmed", ["windows", "linux"], {"file": "client/command/processes/commands.go", "line": 43}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go"], ["loot", "loot-name", "name", "pid", "save", "timeout"], {"request": ["pid", "timeout"], "local": ["loot", "loot-name", "save"], "main": [], "pending": ["name"]}, task([{"rpcMethod": "ProcessDump", "requestType": "ProcessDumpReq", "responseType": "ProcessDump", "taskDescription": "ProcessDumpReq"}], "proposed-native-artifact", "direct-result"), [{"rpcMethod": "ProcessDump", "rpcRequestType": "ProcessDumpReq", "rpcResponseType": "ProcessDump"}]),
  "implant.ps": descriptor("M2", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/processes/commands.go", "line": 21}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["exe", "full", "overflow", "owner", "pid", "print-cmdline", "skip-pages", "timeout", "tree"], {"request": ["full"], "local": ["exe", "overflow", "owner", "pid", "print-cmdline", "skip-pages", "tree"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Ps", "requestType": "PsReq", "responseType": "Ps", "taskDescription": "PsReq"}], "current-preview", "direct-result"), [{"rpcMethod": "Ps", "rpcRequestType": "PsReq", "rpcResponseType": "Ps"}]),
  "implant.psexec": descriptor("M4", "planned", "session-only", ["windows"], {"file": "client/command/exec/commands.go", "line": 257}, ["client/command/exec/psexec.go"], ["binpath", "custom-exe", "profile", "service-description", "service-name", "timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": ["binpath", "custom-exe", "profile", "service-description", "service-name"]}, deferred("Session-gated multistep remote service workflow."), [{"rpcMethod": "ImplantProfiles", "rpcRequestType": "Empty", "rpcResponseType": "ImplantProfiles"}, {"rpcMethod": "Upload", "rpcRequestType": "UploadReq", "rpcResponseType": "Upload"}, {"rpcMethod": "StartService", "rpcRequestType": "StartServiceReq", "rpcResponseType": "ServiceInfo"}, {"rpcMethod": "RemoveService", "rpcRequestType": "RemoveServiceReq", "rpcResponseType": "ServiceInfo"}]),
  "implant.pwd": descriptor("M2", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 122}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Pwd", "requestType": "PwdReq", "responseType": "Pwd", "taskDescription": "PwdReq"}], "current-preview", "direct-result"), [{"rpcMethod": "Pwd", "rpcRequestType": "PwdReq", "rpcResponseType": "Pwd"}]),
  "implant.reconfig": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/reconfig/commands.go", "line": 18}, ["server/rpc/rpc-reconfig.go"], ["beacon-interval", "beacon-jitter", "c2-uri", "reconnect-interval", "timeout"], {"request": ["beacon-interval", "beacon-jitter", "reconnect-interval"], "local": [], "main": ["timeout"], "pending": ["c2-uri"]}, existingMain("beacon.reconfigure", task([{"rpcMethod": "Reconfigure", "requestType": "ReconfigureReq", "responseType": "Reconfigure", "taskDescription": "ReconfigureReq"}], "current-preview", "requires-requery")), [{"rpcMethod": "Reconfigure", "rpcRequestType": "ReconfigureReq", "rpcResponseType": "Reconfigure"}]),
  "implant.registry": descriptor("M2", "planned", "navigation-only", ["windows"], {"file": "client/command/registry/commands.go", "line": 0}, ["client/command/registry/commands.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, navigation("Windows Registry command group; no default RPC."), []),
  "implant.registry.create": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/registry/commands.go", "line": 89}, ["implant/sliver/handlers/handlers_windows.go"], ["hive", "hostname"], {"request": ["hive", "hostname"], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "RegistryCreateKey", "requestType": "RegistryCreateKeyReq", "responseType": "RegistryCreateKey", "taskDescription": "RegistryCreateKeyReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "RegistryCreateKey", "rpcRequestType": "RegistryCreateKeyReq", "rpcResponseType": "RegistryCreateKey"}]),
  "implant.registry.delete": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/registry/commands.go", "line": 105}, ["implant/sliver/handlers/handlers_windows.go"], ["hive", "hostname"], {"request": ["hive", "hostname"], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "RegistryDeleteKey", "requestType": "RegistryDeleteKeyReq", "responseType": "RegistryDeleteKey", "taskDescription": "RegistryDeleteKeyReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "RegistryDeleteKey", "rpcRequestType": "RegistryDeleteKeyReq", "rpcResponseType": "RegistryDeleteKey"}]),
  "implant.registry.list-subkeys": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/registry/commands.go", "line": 121}, ["implant/sliver/handlers/handlers_windows.go"], ["hive", "hostname"], {"request": ["hive", "hostname"], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "RegistryListSubKeys", "requestType": "RegistrySubKeyListReq", "responseType": "RegistrySubKeyList", "taskDescription": "RegistrySubKeyListReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "RegistryListSubKeys", "rpcRequestType": "RegistrySubKeyListReq", "rpcResponseType": "RegistrySubKeyList"}]),
  "implant.registry.list-values": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/registry/commands.go", "line": 137}, ["implant/sliver/handlers/handlers_windows.go"], ["hive", "hostname"], {"request": ["hive", "hostname"], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "RegistryListValues", "requestType": "RegistryListValuesReq", "responseType": "RegistryValuesList", "taskDescription": "RegistryListValuesReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "RegistryListValues", "rpcRequestType": "RegistryListValuesReq", "rpcResponseType": "RegistryValuesList"}]),
  "implant.registry.read": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/registry/commands.go", "line": 33}, ["implant/sliver/handlers/handlers_windows.go"], ["hive", "hostname"], {"request": ["hive", "hostname"], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "RegistryRead", "requestType": "RegistryReadReq", "responseType": "RegistryRead", "taskDescription": "RegistryReadReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "RegistryRead", "rpcRequestType": "RegistryReadReq", "rpcResponseType": "RegistryRead"}]),
  "implant.registry.read.hive": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/registry/commands.go", "line": 49}, ["implant/sliver/handlers/handlers_windows.go"], ["hive", "loot", "name", "save", "type"], {"request": ["hive"], "local": ["loot", "name", "save", "type"], "main": [], "pending": []}, task([{"rpcMethod": "RegistryReadHive", "requestType": "RegistryReadHiveReq", "responseType": "RegistryReadHive", "taskDescription": "RegistryReadHiveReq"}], "proposed-native-artifact", "direct-result"), [{"rpcMethod": "RegistryReadHive", "rpcRequestType": "RegistryReadHiveReq", "rpcResponseType": "RegistryReadHive"}]),
  "implant.registry.write": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/registry/commands.go", "line": 68}, ["implant/sliver/handlers/handlers_windows.go"], ["hive", "hostname", "path", "type"], {"request": ["hive", "hostname", "type"], "local": [], "main": ["path"], "pending": []}, task([{"rpcMethod": "RegistryWrite", "requestType": "RegistryWriteReq", "responseType": "RegistryWrite", "taskDescription": "RegistryWriteReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "RegistryWrite", "rpcRequestType": "RegistryWriteReq", "rpcResponseType": "RegistryWrite"}]),
  "implant.rename": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/reconfig/commands.go", "line": 36}, ["client/command/reconfig/rename.go", "server/rpc/rpc-reconfig.go"], ["name", "timeout"], {"request": ["name"], "local": [], "main": ["timeout"], "pending": []}, existingMain("target.rename"), [{"rpcMethod": "Rename", "rpcRequestType": "RenameReq", "rpcResponseType": "Empty"}]),
  "implant.rev2self": descriptor("M4", "planned", "source-confirmed", ["windows"], {"file": "client/command/privilege/commands.go", "line": 59}, ["implant/sliver/handlers/handlers_windows.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, executionTask("privilege.revert", task([{"rpcMethod": "RevToSelf", "requestType": "RevToSelfReq", "responseType": "RevToSelf", "taskDescription": "RevToSelfReq"}], "proposed-bounded-fetch", "requires-requery")), [{"rpcMethod": "RevToSelf", "rpcRequestType": "RevToSelfReq", "rpcResponseType": "RevToSelf"}]),
  "implant.rm": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 76}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["force", "recursive", "timeout"], {"request": ["force", "recursive"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Rm", "requestType": "RmReq", "responseType": "Rm", "taskDescription": "RmReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Rm", "rpcRequestType": "RmReq", "rpcResponseType": "Rm"}]),
  "implant.runas": descriptor("M4", "planned", "source-confirmed", ["windows"], {"file": "client/command/privilege/commands.go", "line": 21}, ["implant/sliver/handlers/handlers_windows.go"], ["args", "domain", "net-only", "password", "process", "show-window", "timeout", "username"], {"request": [], "local": [], "main": ["timeout"], "pending": ["args", "domain", "net-only", "password", "process", "show-window", "username"]}, executionTask("privilege.run-as", task([{"rpcMethod": "RunAs", "requestType": "RunAsReq", "responseType": "RunAs", "taskDescription": "RunAsReq"}], "proposed-bounded-fetch", "requires-requery")), [{"rpcMethod": "RunAs", "rpcRequestType": "RunAsReq", "rpcResponseType": "RunAs"}]),
  "implant.screenshot": descriptor("M2", "planned", "source-confirmed", ["windows", "linux"], {"file": "client/command/screenshot/commands.go", "line": 20}, ["client/command/screenshot/screenshot.go", "implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go"], ["loot", "name", "save", "timeout"], {"request": [], "local": ["loot", "name", "save"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Screenshot", "requestType": "ScreenshotReq", "responseType": "Screenshot", "taskDescription": "ScreenshotReq"}], "proposed-native-artifact", "direct-result"), [{"rpcMethod": "Screenshot", "rpcRequestType": "ScreenshotReq", "rpcResponseType": "Screenshot"}]),
  "implant.services": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/processes/commands.go", "line": 82}, ["implant/sliver/handlers/handlers_windows.go"], ["host", "timeout"], {"request": ["host"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Services", "requestType": "ServicesReq", "responseType": "Services", "taskDescription": "ServicesReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "Services", "rpcRequestType": "ServicesReq", "rpcResponseType": "Services"}]),
  "implant.services.info": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/processes/commands.go", "line": 98}, ["implant/sliver/handlers/handlers_windows.go"], ["host", "timeout"], {"request": ["host"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "ServiceDetail", "requestType": "ServiceDetailReq", "responseType": "ServiceDetail", "taskDescription": "ServiceDetailReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "ServiceDetail", "rpcRequestType": "ServiceDetailReq", "rpcResponseType": "ServiceDetail"}]),
  "implant.services.start": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/processes/commands.go", "line": 128}, ["implant/sliver/handlers/handlers_windows.go"], ["host", "timeout"], {"request": ["host"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "StartServiceByName", "requestType": "StartServiceByNameReq", "responseType": "ServiceInfo", "taskDescription": "StartServiceByNameReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "StartServiceByName", "rpcRequestType": "StartServiceByNameReq", "rpcResponseType": "ServiceInfo"}]),
  "implant.services.stop": descriptor("M2", "planned", "source-confirmed", ["windows"], {"file": "client/command/processes/commands.go", "line": 113}, ["implant/sliver/handlers/handlers_windows.go"], ["host", "timeout"], {"request": ["host"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "StopService", "requestType": "StopServiceReq", "responseType": "ServiceInfo", "taskDescription": "StopServiceReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "StopService", "rpcRequestType": "StopServiceReq", "rpcResponseType": "ServiceInfo"}]),
  "implant.sideload": descriptor("M4", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/exec/commands.go", "line": 139}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["entry-point", "keep-alive", "loot", "name", "ppid", "process", "process-arguments", "save", "timeout", "unicode"], {"request": [], "local": ["loot", "name", "save"], "main": ["timeout"], "pending": ["entry-point", "keep-alive", "ppid", "process", "process-arguments", "unicode"]}, executionTask("execution.sideload", task([{"rpcMethod": "Sideload", "requestType": "SideloadReq", "responseType": "Sideload", "taskDescription": "SideloadReq"}], "current-execution", "requires-requery")), [{"rpcMethod": "Sideload", "rpcRequestType": "SideloadReq", "rpcResponseType": "Sideload"}]),
  "implant.spawndll": descriptor("M4", "existing", "source-confirmed", ["windows"], {"file": "client/command/exec/commands.go", "line": 168}, ["implant/sliver/handlers/handlers_windows.go"], ["export", "keep-alive", "loot", "name", "ppid", "process", "process-arguments", "save", "timeout"], {"request": [], "local": ["loot", "name", "save"], "main": ["timeout"], "pending": ["export", "keep-alive", "ppid", "process", "process-arguments"]}, executionTask("execution.spawn-dll", task([{"rpcMethod": "SpawnDll", "requestType": "SpawnDllReq", "responseType": "SpawnDll", "taskDescription": "SpawnDllReq", "rpcRequestType": "InvokeSpawnDllReq"}], "current-execution", "requires-requery")), [{"rpcMethod": "SpawnDll", "rpcRequestType": "InvokeSpawnDllReq", "rpcResponseType": "SpawnDll"}]),
  "implant.ssh": descriptor("M4", "planned", "pending-runtime", ["windows", "linux", "darwin"], {"file": "client/command/exec/commands.go", "line": 284}, ["client/command/exec/ssh.go", "server/rpc/rpc-shell.go"], ["kerberos-config", "kerberos-keytab", "kerberos-realm", "login", "password", "port", "private-key", "skip-loot", "timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": ["kerberos-config", "kerberos-keytab", "kerberos-realm", "login", "password", "port", "private-key", "skip-loot"]}, deferred("Pinned implant has a handler, but the console workflow is session-gated; beacon path needs separate proof."), [{"rpcMethod": "RunSSHCommand", "rpcRequestType": "SSHCommandReq", "rpcResponseType": "SSHCommand"}]),
  "implant.tail": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 310}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["bytes", "colorize-output", "file-type", "hex", "lines", "loot", "name", "timeout", "type"], {"request": ["bytes", "lines"], "local": ["colorize-output", "file-type", "hex", "loot", "name", "type"], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Download", "requestType": "DownloadReq", "responseType": "Download", "taskDescription": "DownloadReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "Download", "rpcRequestType": "DownloadReq", "rpcResponseType": "Download"}]),
  "implant.tasks": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/tasks/commands.go", "line": 19}, ["server/rpc/rpc-beacons.go"], ["filter", "overflow", "skip-pages", "timeout"], {"request": [], "local": ["overflow", "skip-pages"], "main": ["timeout"], "pending": ["filter"]}, existingMain("beacon.tasks.read"), [{"rpcMethod": "GetBeaconTasks", "rpcRequestType": "Beacon", "rpcResponseType": "BeaconTasks"}]),
  "implant.tasks.cancel": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/tasks/commands.go", "line": 49}, ["server/rpc/rpc-beacons.go"], [], {"request": [], "local": [], "main": [], "pending": []}, existingMain("beacon.tasks.cancel"), [{"rpcMethod": "CancelBeaconTask", "rpcRequestType": "BeaconTask", "rpcResponseType": "BeaconTask"}]),
  "implant.tasks.fetch": descriptor("M1", "existing", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/tasks/commands.go", "line": 37}, ["server/rpc/rpc-beacons.go"], [], {"request": [], "local": [], "main": [], "pending": []}, existingMain("beacon.tasks.read"), [{"rpcMethod": "GetBeaconTaskContent", "rpcRequestType": "BeaconTask", "rpcResponseType": "BeaconTask"}]),
  "implant.terminate": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/processes/commands.go", "line": 67}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["force", "timeout"], {"request": ["force"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Terminate", "requestType": "TerminateReq", "responseType": "Terminate", "taskDescription": "TerminateReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Terminate", "rpcRequestType": "TerminateReq", "rpcResponseType": "Terminate"}]),
  "implant.upload": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/filesystem/commands.go", "line": 185}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go"], ["ioc", "overwrite", "timeout"], {"request": ["ioc", "overwrite"], "local": [], "main": ["timeout"], "pending": []}, task([{"rpcMethod": "Upload", "requestType": "UploadReq", "responseType": "Upload", "taskDescription": "UploadReq"}], "proposed-bounded-fetch", "requires-requery"), [{"rpcMethod": "Upload", "rpcRequestType": "UploadReq", "rpcResponseType": "Upload"}]),
  "implant.wasm": descriptor("M8", "planned", "unsupported", ["windows", "linux", "darwin"], {"file": "client/command/wasm/commands.go", "line": 21}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go", "implant/sliver/handlers/tun.go"], ["dir", "file", "loot", "pipe", "skip-registration", "timeout"], {"request": [], "local": ["loot"], "main": ["timeout"], "pending": ["dir", "file", "pipe", "skip-registration"]}, deferred("WASM execution uses a tunnel; no pinned beacon task dispatch path."), [{"rpcMethod": "RegisterWasmExtension", "rpcRequestType": "RegisterWasmExtensionReq", "rpcResponseType": "RegisterWasmExtension"}, {"rpcMethod": "ListWasmExtensions", "rpcRequestType": "ListWasmExtensionsReq", "rpcResponseType": "ListWasmExtensions"}, {"rpcMethod": "ExecWasmExtension", "rpcRequestType": "ExecWasmExtensionReq", "rpcResponseType": "ExecWasmExtension"}, {"rpcMethod": "CreateTunnel", "rpcRequestType": "Tunnel", "rpcResponseType": "Tunnel"}, {"rpcMethod": "CloseTunnel", "rpcRequestType": "Tunnel", "rpcResponseType": "Empty"}]),
  "implant.wasm.ls": descriptor("M8", "planned", "pending-runtime", ["windows", "linux", "darwin"], {"file": "client/command/wasm/commands.go", "line": 49}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go", "implant/sliver/handlers/tun.go"], [], {"request": [], "local": [], "main": [], "pending": []}, task([{"rpcMethod": "ListWasmExtensions", "requestType": "ListWasmExtensionsReq", "responseType": "ListWasmExtensions", "taskDescription": "ListWasmExtensionsReq"}], "proposed-bounded-fetch", "direct-result"), [{"rpcMethod": "ListWasmExtensions", "rpcRequestType": "ListWasmExtensionsReq", "rpcResponseType": "ListWasmExtensions"}]),
  "implant.wg-socks": descriptor("M5", "planned", "pending-runtime", ["windows", "linux", "darwin"], {"file": "client/command/wireguard/commands.go", "line": 90}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go", "client/command/wireguard/commands.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, deferred("Conditional IncludeWG beacon handler; console workflow requires a WG session and live build proof."), [{"rpcMethod": "WGListSocksServers", "rpcRequestType": "WGSocksServersReq", "rpcResponseType": "WGSocksServers"}], WG_TRANSPORT),
  "implant.wg-socks.start": descriptor("M5", "planned", "pending-runtime", ["windows", "linux", "darwin"], {"file": "client/command/wireguard/commands.go", "line": 104}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go", "client/command/wireguard/commands.go"], ["bind"], {"request": ["bind"], "local": [], "main": [], "pending": []}, deferred("Conditional IncludeWG beacon handler; console workflow requires a WG session and live build proof."), [{"rpcMethod": "WGStartSocks", "rpcRequestType": "WGSocksStartReq", "rpcResponseType": "WGSocks"}], WG_TRANSPORT),
  "implant.wg-socks.stop": descriptor("M5", "planned", "pending-runtime", ["windows", "linux", "darwin"], {"file": "client/command/wireguard/commands.go", "line": 117}, ["implant/sliver/handlers/handlers_windows.go", "implant/sliver/handlers/handlers_linux.go", "implant/sliver/handlers/handlers_darwin.go", "client/command/wireguard/commands.go"], [], {"request": [], "local": [], "main": [], "pending": []}, deferred("Conditional IncludeWG beacon handler; console workflow requires a WG session and live build proof."), [{"rpcMethod": "WGStopSocks", "rpcRequestType": "WGSocksStopReq", "rpcResponseType": "WGSocks"}], WG_TRANSPORT),
  "implant.whoami": descriptor("M2", "planned", "source-confirmed", ["windows", "linux", "darwin"], {"file": "client/command/info/commands.go", "line": 91}, ["client/command/info/info.go", "implant/sliver/handlers/handlers_windows.go"], ["timeout"], {"request": [], "local": [], "main": ["timeout"], "pending": []}, hybrid(["username"], [{"rpcMethod": "CurrentTokenOwner", "requestType": "CurrentTokenOwnerReq", "responseType": "CurrentTokenOwner", "taskDescription": "CurrentTokenOwnerReq"}]), [{"rpcMethod": "CurrentTokenOwner", "rpcRequestType": "CurrentTokenOwnerReq", "rpcResponseType": "CurrentTokenOwner"}]),
} as const satisfies Readonly<Record<string, BeaconCommandDescriptor>>);

export type BeaconCommandId = keyof typeof BEACON_COMMAND_MATRIX;
export type BeaconCommandAvailabilityReason = "unknown-command" | "requires-beacon" | "not-delivered" | "unverified-runtime" | "unsupported-platform" | "unsupported-architecture" | "unsupported-transport" | "non-task-route";
export type BeaconCommandAvailability = { readonly available: true } | { readonly available: false; readonly reason: BeaconCommandAvailabilityReason };

/** Source-matrix gate only. Dispatch still requires the existing exact-target, server-support, and operation-review checks. */
export function beaconCommandCapability(id: string, target: TargetSummary): BeaconCommandAvailability {
  if (!Object.hasOwn(BEACON_COMMAND_MATRIX, id)) return { available: false, reason: "unknown-command" };
  const row = BEACON_COMMAND_MATRIX[id as BeaconCommandId];
  if (target.mode !== "beacon") return { available: false, reason: "requires-beacon" };
  if (row.delivery !== "existing") return { available: false, reason: "not-delivered" };
  if (row.support !== "source-confirmed") return { available: false, reason: "unverified-runtime" };
  if (!row.platforms.includes(target.os.trim().toLowerCase() as BeaconCommandPlatform)) return { available: false, reason: "unsupported-platform" };
  const platform = target.os.trim().toLowerCase() as BeaconCommandPlatform;
  const architecture = target.arch.trim().toLowerCase() as "386" | "amd64" | "arm64";
  if (!row.architecturesByPlatform[platform]?.includes(architecture as never)) {
    return { available: false, reason: "unsupported-architecture" };
  }
  if (!row.transports.includes(target.transport)) return { available: false, reason: "unsupported-transport" };
  if (row.route.kind === "navigation" || row.route.kind === "operator-workflow" || row.route.kind === "deferred-workflow") {
    return { available: false, reason: "non-task-route" };
  }
  return { available: true };
}

function deepFreeze<Value>(value: Value): Value {
  if (typeof value !== "object" || value === null || Object.isFrozen(value)) return value;
  for (const child of Object.values(value)) deepFreeze(child);
  return Object.freeze(value);
}
